baseurl: 'https://school-brainhack.github.io'
title: 'BrainHack School'
theme: hugo-universal-theme
defaultContentLanguage: en
defaultContentLanguageInSubdir: FALSE

outputFormats:
  Calendar:
    mediaType: text/calendar

languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    taxonomies:
      tag: tags
      category: categories
      name: names
    enableGitInfo: TRUE
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: Schedule
          name: Schedule
          url: /schedule/
          weight: 2
        - identifier: Projects
          name: Projects
          url: /project/
          weight: 3
        - identifier: Weeks
          name: Weeks
          url: /weeks/
          weight: 4
        - identifier: Locations
          name: Locations
          url: /locations/
          weight: 5
        - identifier: Register
          name: Register
          url: /register/
          weight: 6
        - parent: documents
          name: Getting started
          url: /guide/
          weight: 7
        - parent: documents
          name: Project guide
          url: /project_guide/
          weight: 8
        - parent: documents
          name: Code of Conduct
          url: /coc/
          weight: 9
        - identifier: Modules
          name: Modules
          url: /modules/
          weight: 10

      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/school-brainhack'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 3
          name: Mastodon
          url: 'https://neuromatch.social/@brainhack_school'
          pre: <i class='fab fa-2x fa-twitter'></i>
        - weight: 4
          name: Email
          url: 'mailto:school.brainhack@gmail.com'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      outputFormats:
        Calendar:
          mediaType: text/calendar
      viewMorePostLink: /blog/
      author:
      defaultKeywords:
        - BrainHack
        - Neuroscience
      mainSections:
        - blog
      defaultDescription: Brainhack School
      facebook_site: ''
      twitter_site: BrainhackMTL
      default_sharing_image: img/brainhackSchool.jpg
      googleMapsApiKey:
      style: green
      email:
      contact_form_ajax: false
      about_us: >-
        <p>Fundamentals and project in neural data science.</p>
      copyright: 'Copyright (c) 2023, BrainHack School; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>BrainHack School</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: true
      instructors:
        enable: true
      features:
        enable: false
      testimonials:
        enable: true
        title: Why Brainhack School?
        subtitle: >-
          Coding and other data science skills are much better acquired and
          solidified through practice. After a one week bootcamp, most of the
          brainhack training consists of open and collaborative work on a project of
          your choice.
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Project-based, transdisciplinary training'
        subtitle: 'Neuroscience, Statistical Modelling and Computer Science'
        link_url: https://https://school-brainhack.github.io/
        link_text: "Check out the 2020 lectures and projects"
      clients:
        enable: true
        title: Partner institutions
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: false
        text: "**:computer: :brain: Contact <school.brainhack@gmail.com> to register! :brain: :computer:**: "


  fr:
    languageCode: fr
    languageName: Français
    contentDir: content/fr
    title: 'École BrainHack'
    weight: 2
    taxonomies:
      tag: tags
      category: categories
      name: names
    menu:
      main:
        - identifier: home
          name: Accueil
          url: /
          weight: 1
        - identifier: Schedule
          name: Schedule
          url: /schedule/
          weight: 2
        - identifier: Weeks
          name: Weeks
          url: /weeks/
          weight: 4
        - identifier: Locations
          name: Locations
          url: /locations/
          weight: 5
        - identifier: Register
          name: Register
          url: /register/
          weight: 6
        - parent: documents
          name: Guide de démarrage rapide
          url: /fr/guide/
          weight: 7


      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/school-brainhack'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 3
          name: Mastodon
          url: 'https://neuromatch.social/@brainhack_school'
          pre: <i class='fab fa-2x fa-twitter'></i>
        - weight: 4
          name: Email
          url: 'mailto:school.brainhack@gmail.com'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      viewMorePostLink: /blog/
      author:
      defaultKeywords:
        - Science des données
        - Neuroscience
      mainSections:
        - blog
      defaultDescription:
      facebook_site: ''
      twitter_site: BrainhackMTL
      default_sharing_image: img/sharing-default.png
      googleMapsApiKey:
      style: green
      email: school.brainhack@gmail.com
      contact_form_ajax: false
      about_us: >-
        <p>Apprentissage basé projet en sciences des données neuronales.</p>
      copyright: 'Copyright (c) 2023, BrainHack School; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>BrainHack School</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: true
      instructors:
        enable: true
      features:
        enable: false
      testimonials:
        enable: true
        title: Pourquoi Brainhack School?
        subtitle: >-
          L'apprentissage par la pratique est très bien adapté pour la programmation et les autres compétences utiles en sciences des données. Après une semaine intensive de présentations,
          la majorité de la formation Brainhack consiste en un projet de votre choix, réalisé de votre de manière ouverte et collaborative.
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Formation transdisciplinaire axée sur les projets'
        subtitle: 'Neurosciences, Modélisation statistique et Sciences informatiques'
        link_url: https://school-brainhack.github.io/fr/
        link_text: Consultez les projets et vidéos de 2020
      clients:
        enable: true
        title: Institutions partenaires
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: false
        text: "**:computer: :brain: Contactez <school.brainhack@gmail.com> pour vous inscrire! :brain: :computer:**"

Permalinks:
  blog: '/blog/:year/:month/:day/:filename/'

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3


disqusShortname: ''
googleAnalytics: ''
paginate: 10
